### ISSUE TITLE
New mtgo league data

### ISSUE THREAD

**Issue by Never28** [Badaro/MTGODecklistCache.Tools#2]
Hi, this was meant to be a private message but github doesn't allow those so I'll open an issue instead. First, I want to compliment you for the great work you did with the parser and cacher, I played around a bit in these days following the changes Wotc made on how they publish results on their site and I was blown away by what it offers.

It seems that right now Wotc is publishing league results containing at random 25 lists that did 5-0, and they change with each refresh, but if you go and check with dev tools you can find the actual list of all the decks that did 3 wins or more (I attach a json for a modern league [modern-league-2023-12-157787.json](https://github.com/Badaro/MTGODecklistCache.Tools/files/13722003/modern-league-2023-12-157787.json)). If this change is permanent, that would mean that league results can be used to get a meta breakdown and more other things.

With some adjustment to the code, this is what I got processing the data from modern leagues  for the Lost Cavern of Ixalan meta and post Fury and Beans ban
![image](https://github.com/Badaro/MTGODecklistCache.Tools/assets/12485615/59a548f9-f3bf-4293-8e85-c15db6cfdbeb)
![image](https://github.com/Badaro/MTGODecklistCache.Tools/assets/12485615/5ce3b161-bb8b-4ead-b39f-8e0da5067c44)

I would also like to put down some more friendly UI to make queries and show data (something with Angular or React), if something good comes out and you are interested I can share the project with you.

**Comment by Badaro** [comment]
Yeah, I just noticed the page is back and was peeking at the new structure.

> It seems that right now Wotc is publishing league results containing at random 25 lists that did 5-0, and they change with each refresh, but if you go and check with dev tools you can find the actual list of all the decks that did 3 wins or more (I attach a json for a modern league [modern-league-2023-12-157787.json](https://github.com/Badaro/MTGODecklistCache.Tools/files/13722003/modern-league-2023-12-157787.json)). If this change is permanent, that would mean that league results can be used to get a meta breakdown and more other things.

This is the same behavior I noticed when I was rewriting the scraper over the weekend, though the page structure has changed again (this JSON was previously being embedded into the HTML page, now it's an external API call). 

I was actually halfway into a rewrite for their new structure when the site went down... you can see my WIP on the `mtgo-scraping-fix branch`.

Anyway, since I'm scraping directly from the JSON if this is the "new" behavior I'll be automatically getting the full data as you suggested.

I created #3 to track the implementation of the new scraper so I'll close this ticket, but you can follow progress there.

**Comment by Never28** [comment]
Same thing is happening for challenges as well, they show more than just the top64.

**Comment by Badaro** [comment]
Challenges and prelims are straight up showing all decks from the event. :)

**Comment by Badaro** [comment]
Test data from the new scraper available in this branch:
https://github.com/Badaro/MTGODecklistCache/tree/new-mtgo-data

**Comment by Never28** [comment]
They changed it again, now the API only returns the actual 5-0, no more 3-2 and 4-1 :)

**Comment by Badaro** [comment]
Not too surprising, that did look very much like a bug. And given the amount of data it was loading was probably not being good for their servers as well.

At least it looks like giving full data for challengs and prelims was intentional, and that's a big step forward.
